### PR TITLE
simple_http: when writing fails, try (once) to reconnect the socket

### LINKED ISSUE #79: HttpResponseTooShort for first request after a while
I have this strange behaviour with a Discord bot that I'm currently making.

For a cryptocurrency project, I am using rust-jsonrpc as a client to query that cryptocurrency's blockchain. It uses the same RPC mechanism that Bitcoin uses, so I'm using this crate and it has been working fine for quite some time.

Because I have to do many RPCs, I store an instance of a rust-jsonrpc client as global data of the bot. This global data is essentially a `Box::pin(async move { Data } )` where I store the client as a member of Data. (the bot is made using [poise](https://docs.rs/poise/latest/poise/#quickstart), and in [this](https://docs.rs/poise/latest/src/poise/framework/builder.rs.html#68-81) `setup` function is where Data gets initiated)

When I start the bot and keep it running for a while (30+ sec) and get the client from global data and do a `getnewaddress` RPC, I am getting a HttpResponseTooShort error: `error: JsonRPC(Transport(HttpResponseTooShort { actual: 0, needed: 12 }))`. It happens every time I use this call after at least 30 seconds of idling and I can't figure out why this happens. A second request within 30 seconds works just fine.

I've already checked if the problem is keeping a client around for a while:

```rs
    let client = vrsc_rpc::Client::vrsc(true, Auth::ConfigFile).unwrap();

    thread::sleep(Duration::from_secs(50));

    dbg!(client.get_new_address().unwrap());
```
_(I built a wrapper like https://github.com/rust-bitcoin/rust-bitcoincore-rpc for this cryptocurrency project)_

This doesn't appear to be a problem. I can't figure out what is, though. My guess would be that I keep a connection open for too long, but I can't figure this out, as it appears to be working in a separate environment.

Any ideas?

### PR DESCRIPTION
**Pull request by apoelstra**
Attempt at #79. Does not fix the issue, but will merge this anyway since it fixes an issue I've hit in other projects.

### CODE REVIEW

File: src/simple_http.rs [hunk 1]
```diff
@@ -177,24 +177,36 @@ impl SimpleHttpTransport {
...
+            // case.
+            //
+            // From http://www.softlab.ntua.gr/facilities/documentation/unix/unix-socket-faq/unix-socket-faq-2.html
+            // "If the peer calls close() or exits...I would expect EPIPE, not on the next call,
+            // but the one after."
+            if write_sock.write_all(b"PO").is_err() || write_sock.write_all(b"ST ").is_err() {
+                **write_sock.get_mut() = self.fresh_socket()?;
+                write_sock.write_all(b"POST ")?;
+            }
+            write_sock.write_all(b"POST ")?;
```
Comment (tcharding) [inline src/simple_http.rs:193]: Why the second write of "POST" (excluding the error path)? At this stage we've either written POST already or returned an error?

Comment (apoelstra) [reply src/simple_http.rs]: Oh, derp, this second POST should not be there and probably completely breaks things. Pushed to remove it.

**Review by tcharding — APPROVED** [review]
ACK 5b7b23c0b3411f758ba2c4249908fbc8208b9e76
